# Generated by Django 5.0.1 on 2024-01-21 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=100)),
                ('customerEmail', models.CharField(max_length=100)),
                ('customerPhone', models.CharField(max_length=100)),
                ('foodType', models.CharField(max_length=100)),
                ('foodName', models.CharField(max_length=100)),
                ('foodPrice', models.CharField(max_length=100)),
            ],
        ),
    ]
