# Generated by Django 5.0.1 on 2024-01-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customerEmail',
        ),
    ]
