# Generated by Django 5.0.1 on 2024-01-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_order_customeremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderId',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
